### ISSUE TITLE
Invalid description

### ISSUE THREAD

**Issue by MetalGearDaner** [Coutume/ImageOnMap#4]
Using latest version from source code:

Could not load 'plugins/ImageOnMap.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[spigot-1.8.jar:git-Spigot-6d85d97-b389396]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.8.jar:git-Spigot-6d85d97-b389396]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:290) [spigot-1.8.jar:git-Spigot-6d85d97-b389396]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigot-1.8.jar:git-Spigot-6d85d97-b389396]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot-1.8.jar:git-Spigot-6d85d97-b389396]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more

**Comment by prokopyl** [comment]
You instantly closed the issue, was that an error on your side, or did you miss-click ?
About the problem itself : in revision 6474acecdf0223b41bbe9fd1b46b1d65f7c0b5c5 we switched the project building system to Maven, so the data files (including plugin.yml) aren't in the same directory anymore.

**Comment by MetalGearDaner** [comment]
Sorry, I have just noticed that I have compiled the plugin without the plugin.yml and config.yml files haha. Thanks a lot for the update, I have been checking it with my staff partners and everything works appropiately :)
